# In this directory, run the following command to build this builder.
steps:
- id: pull_cache_image
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest || exit 0
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: [ 
          'build', 
          '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest', 
          '--cache-from', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest',
          '-f', 'docker/pdfService.dev.dockerfile', 
          '--no-cache',
          '.' 
        ]
  
- id: deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'microservices/pdfService/app.yaml', '--quiet', '--verbosity=debug']
  timeout: 900s
  waitFor:
    - build

timeout: 1200s
substitutions:
  _IMAGE_NAME: pdfService-image
options:
  machineType: 'N1_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
tags: ['pdf-service', 'dev']
images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']