# In this directory, run the following command to build this builder.
# $ gcloud builds submit --config cloudbuild.yaml .
steps:
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '-f', 'docker/server.dev.dockerfile', '.' ]
  
- id: deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', 'server/app.yaml']
  timeout: 900s
  waitFor:
    - build

timeout: 1600s
substitutions:
  _IMAGE_NAME: gcp-demo-image
options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['gcp-demo', 'dev']
images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}']