###
GET http://localhost:4300/api/ping
content-type: application/json

###
GET http://localhost:4300/api/users
content-type: application/json

###
GET http://localhost:4300/api/users/1
content-type: application/json


###
GET http://localhost:4300/api/messages
content-type: application/json

###
GET http://localhost:4300/api/messages/1
content-type: application/json

###
POST  http://localhost:4300/api/messages
content-type: application/json

{
    "text": "hello 123"
}

###
DELETE  http://localhost:4300/api/messages/1
content-type: application/json


###
GET https://balmy-channel-211708.appspot.com/api/users
content-type: application/json

###
GET https://balmy-channel-211708.appspot.com/api/ping
content-type: application/json