runtime: nodejs
env: flex
service: default

env_variables:
  NODE_ENV: dev

network:
  forwarded_ports:
    - 4300/tcp

instance_class: F2

manual_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120
  max_concurrent_requests: 30
  cpu_utilization:
    target_utilization: 0.5

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
