runtime: nodejs
env: flex
service: default

env_variables:
  NODE_ENV: dev
  RUN_PORT: 4300
network:
  forwarded_ports:
    - 4300/tcp

instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  max_concurrent_requests: 20
  cpu_utilization:
    target_utilization: 0.7

health_check:
  enable_health_check: false